# Build context for this Dockerfile MUST BE the project root (should be .. if this file is in ./.ci/)

ARG GATEWAY_IMAGE=${GATEWAY_IMAGE}
ARG KONG_MANAGER_BUILD_SHA1=${KONG_MANAGER_BUILD_SHA1}

FROM $GATEWAY_IMAGE
LABEL com.konghq.kong-manager.build="${KONG_MANAGER_BUILD_SHA1}"

ADD ./dist /usr/local/kong/gui
