version: "3.9"

services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  kong-test-image:
    # Using a empty string as the fallback makes this env optional but still fails if not set when used
    image: "${GATEWAY_TEST_IMAGE:- }"
    security_opt:
      - no-new-privileges:true
    build:
      context: ${GITHUB_WORKSPACE:-..} # MUST BE the project root (should be .. here as we're in ./.ci/)
      dockerfile: .ci/Dockerfile.test-image # relative to the build context
      args:
        # Using a empty string as the fallback makes this env optional but still fails if not set when used
        GATEWAY_IMAGE: "${GATEWAY_IMAGE:- }"
        KONG_MANAGER_BUILD_SHA1: "${KONG_MANAGER_BUILD_SHA1:-null}"

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  kong-db:
    image: "postgres:13"
    security_opt:
      - no-new-privileges:true
    hostname: kong-db
    command: "-c max_connections=5000"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  kong:
    &kong
    # Using a empty string as the fallback makes this env optional but still fails if not set when used
    image: "${GATEWAY_IMAGE:- }"
    security_opt:
      - no-new-privileges:true
    hostname: kong
    command: 'sh -c "kong migrations bootstrap && kong start"'
    ports:
      - "8000-8002:8000-8002"
    environment:
      &kong-environment
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_ROUTER_FLAVOR:
    restart: always
    depends_on:
      &kong-depends_on
      kong-db:
        condition: service_healthy

  kong-gen-cert:
    # Using a empty string as the fallback makes this env optional but still fails if not set when used
    image: "${GATEWAY_IMAGE:- }"
    security_opt:
      - no-new-privileges:true
    command: >-
      sh -c "kong hybrid gen_cert /tmp/hybrid/cluster.crt /tmp/hybrid/cluster.key"
    volumes:
      - "${GITHUB_WORKSPACE:-.}/hybrid:/tmp/hybrid:z"

  kong-hybrid-cp:
    <<: *kong
    command: >-
      sh -c "kong migrations bootstrap && kong migrations up && kong migrations finish && kong start"
    ports:
      - "8001-8006:8001-8006"
    environment:
      <<: *kong-environment
      KONG_PG_DATABASE: kong
      KONG_ROLE: control_plane
      KONG_CLUSTER_CERT: /tmp/hybrid/cluster.crt
      KONG_CLUSTER_CERT_KEY: /tmp/hybrid/cluster.key
    volumes:
      - "${GITHUB_WORKSPACE:-.}/hybrid:/tmp/hybrid"

  kong-hybrid-dp:
    <<: *kong
    hostname: "" # no hostname for data planes
    ports: [] # no ports for data planes
    command: sh -c "kong start"
    environment:
      KONG_DATABASE: off
      KONG_ROLE: data_plane
      KONG_CLUSTER_CERT: /tmp/hybrid/cluster.crt
      KONG_CLUSTER_CERT_KEY: /tmp/hybrid/cluster.key
      KONG_CLUSTER_CONTROL_PLANE: kong-hybrid-cp:8005
      KONG_CLUSTER_TELEMETRY_ENDPOINT: kong-hybrid-cp:8006
    volumes:
      - "${GITHUB_WORKSPACE:-.}/hybrid:/tmp/hybrid"
    depends_on:
      - kong-hybrid-cp # so that we can start the control plane by scaling the data planes
