name: 🐞 Bug
description: Something is not working as expected.
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. Make sure you are also using the latest version of Kong.
    options:
    - label: I have searched the existing issues
      required: true
- type: input 
  attributes:
    label: Kong version (`$ kong version`)
    description: 'example: Kong 3.4'
    placeholder: 'Please provide the current Kong Gateway version you are using here.'
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```...```
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: When I do <X>, <Z> should happen instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Click the <X> button...
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      - Kong configuration (the output of a GET request to Kong's Admin port - see
        https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
      - Running operating system/browser and version
      - Console output and network log of the browser's developer tools
  validations:
    required: false