blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/Kong/kong-manager/discussions/categories/ideas
    about: Propose your cool ideas and feature requests at the Kong Manager discussion forum
  - name: Question
    url: https://github.com/Kong/kong-manager/discussions/categories/q-a
    about: Ask (and answer) questions at the Kong Manager discussion forum