import '@material-design-icons/font'
import '@kong-ui-public/app-layout/dist/style.css'
import '@kong-ui-public/entities-certificates/dist/style.css'
import '@kong-ui-public/entities-consumer-credentials/dist/style.css'
import '@kong-ui-public/entities-consumers/dist/style.css'
// import '@kong-ui-public/entities-data-plane-nodes/dist/style.css'
import '@kong-ui-public/entities-gateway-services/dist/style.css'
import '@kong-ui-public/entities-key-sets/dist/style.css'
import '@kong-ui-public/entities-keys/dist/style.css'
import '@kong-ui-public/entities-plugins/dist/style.css'
import '@kong-ui-public/entities-routes/dist/style.css'
import '@kong-ui-public/entities-snis/dist/style.css'
import '@kong-ui-public/entities-upstreams-targets/dist/style.css'
import '@kong-ui-public/entities-vaults/dist/style.css'
import '@kong-ui-public/forms/dist/style.css'
import '@kong-ui-public/misc-widgets/dist/style.css'
import '@kong/kongponents/dist/style.css'

import './bootstrap-grid.css'
import './typography.scss'
import './reboot.scss'
import './form.scss'
import './fonts.css'
import './inputs.scss'
