import '@kong/kongponents/dist/style.css'
import '@kong-ui/entities-gateway-services/dist/style.css'
import '@kong-ui/entities-consumers/dist/style.css'
import '@kong-ui/entities-plugins/dist/style.css'
import '@kong-ui/entities-upstreams-targets/dist/style.css'
import '@kong-ui/entities-vaults/dist/style.css'
import '@kong-ui/entities-keys/dist/style.css'
import '@kong-ui/entities-key-sets/dist/style.css'
