# This is a reusable workflow

name: Install Dependencies, Run Lint & Build

on:
  workflow_call:

jobs:
  lint:
    name: Run lint
    runs-on: ${{ vars.RUNS_ON }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0 version is determined from the packageManager field in package.json by default.

      - id: setup-node
        name: Setup Node
        timeout-minutes: 5
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependency
        timeout-minutes: 5
        run: pnpm install

      - name: Run lint
        timeout-minutes: 10
        run: pnpm lint

  build-release:
    name: Build release
    runs-on: ${{ vars.RUNS_ON }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0 version is determined from the packageManager field in package.json by default.

      - id: setup-node
        name: Setup Node
        timeout-minutes: 5
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        timeout-minutes: 5
        run: pnpm install

      - name: Build release
        timeout-minutes: 10
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          pnpm build
          echo "${{ github.sha }}" > dist/build.sha1

      - name: Pack release
        run: tar -cvzf ./release.tar.gz dist/*

      - name: Upload release
        timeout-minutes: 5
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./release.tar.gz

      - name: Upload bundle-analyzer
        timeout-minutes: 5
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analyzer
          path: bundle-analyzer/
