name: Test Container Perm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  test-container-perm:
    name: Test Container Perm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Test Container Perm
        timeout-minutes: 10
        working-directory: ${{ github.workspace }}
        run: |
          id
          mkdir -p ./hybrid
          chmod a+w ./hybrid
          docker compose -f .ci/docker-compose.yml up kong-gen-cert
